# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1498574914);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1498575034);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1498574554);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 1498575274);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1498574794);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1498574674);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1498575154);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1498599117461");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1498600922461");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1498599118473");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1498602718473");
user_pref("browser.search.countryCode", "PH");
user_pref("browser.search.region", "PH");
user_pref("browser.slowStartup.averageTime", 3024);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20170125001729");
user_pref("browser.startup.homepage_override.mstone", "45.7.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1498660833989");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1498574496274");
user_pref("datareporting.policy.firstRunTime", "1498574433989");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.firstPaint", 3818);
user_pref("datareporting.sessions.current.main", 161);
user_pref("datareporting.sessions.current.sessionRestored", 3001);
user_pref("datareporting.sessions.current.startTime", "1498599107853");
user_pref("datareporting.sessions.current.totalTime", 27);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1498574433013,\"a\":8,\"t\":749,\"c\":false,\"m\":181,\"fp\":2642,\"sr\":3254}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.7.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1498574927);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.7.0");
user_pref("extensions.lastPlatformVersion", "45.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1485315957000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485315956000}}}");
user_pref("gecko.buildID", "20170125001729");
user_pref("gecko.mstone", "45.7.0");
user_pref("idle.lastDailyNotification", 1498575403);
user_pref("media.gmp-manager.buildID", "20170125001729");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 52702);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1498599108);
user_pref("toolkit.telemetry.cachedClientID", "cd134c67-ae98-4a55-84ee-c5180d860513");
user_pref("toolkit.telemetry.previousBuildID", "20170125001729");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
